import type {
  FloorPlanTable,
  FloorPlanSection,
  FloorPlanDivider,
  FloorPlanDecoration,
  FloorPlanMetadata,
} from '@/store/api/floorPlansApi';

export interface FloorPlanTemplate {
  name: string;
  description: string;
  tables: FloorPlanTable[];
  sections: FloorPlanSection[];
  dividers: FloorPlanDivider[];
  decorations: FloorPlanDecoration[];
  metadata: FloorPlanMetadata;
}

// Professional color palette
const wallsColor = 'rgba(30, 41, 59, 0.65)';
const mainDiningColor = 'rgba(34, 197, 94, 0.18)';
const barZoneColor = 'rgba(14, 165, 233, 0.20)';
const privateZoneColor = 'rgba(239, 68, 68, 0.18)';
const serviceAisleColor = 'rgba(148, 163, 184, 0.15)';

export const CLASSIC_RESTAURANT_TEMPLATE: FloorPlanTemplate = {
  name: 'Classic Bistro Layout',
  description:
    'Traditional symmetrical restaurant with two columns of uniform tables flanking a central service aisle. Perfect for efficient service flow and elegant dining atmosphere. 20 tables total (10 per side).',
  metadata: {
    canvasWidth: 1400,
    canvasHeight: 1400,
    backgroundColor: 'hsl(var(--background))',
    backgroundImage: undefined,
    gridSize: 20,
    showGrid: true,
    zoomLevel: 1,
  },
  tables: [
    // ========================================
    // LEFT COLUMN - 10 Tables (Evenly Spaced)
    // Starting from top, working down to entrance
    // ========================================
    {
      id: 'left-1',
      x: 350,
      y: 200,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L1',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-2',
      x: 350,
      y: 310,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L2',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-3',
      x: 350,
      y: 420,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L3',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-4',
      x: 350,
      y: 530,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L4',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-5',
      x: 350,
      y: 640,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L5',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-6',
      x: 350,
      y: 750,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L6',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-7',
      x: 350,
      y: 860,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L7',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-8',
      x: 350,
      y: 970,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L8',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-9',
      x: 350,
      y: 1080,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L9',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'left-10',
      x: 350,
      y: 1190,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'L10',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },

    // ========================================
    // RIGHT COLUMN - 10 Tables (Perfect Mirror)
    // Starting from top, working down to entrance
    // ========================================
    {
      id: 'right-1',
      x: 940,
      y: 200,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R1',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-2',
      x: 940,
      y: 310,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R2',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-3',
      x: 940,
      y: 420,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R3',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-4',
      x: 940,
      y: 530,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R4',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-5',
      x: 940,
      y: 640,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R5',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-6',
      x: 940,
      y: 750,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R6',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-7',
      x: 940,
      y: 860,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R7',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-8',
      x: 940,
      y: 970,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R8',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-9',
      x: 940,
      y: 1080,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R9',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'right-10',
      x: 940,
      y: 1190,
      width: 110,
      height: 110,
      rotation: 0,
      shape: 'rectangle',
      label: 'R10',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },

    // ========================================
    // BAR AREA - Small tables near top
    // ========================================
    {
      id: 'bar-1',
      x: 200,
      y: 220,
      width: 80,
      height: 80,
      rotation: 0,
      shape: 'circle',
      label: 'B1',
      capacity: 2,
      zone: 'Bar Area',
      color: barZoneColor,
    },
    {
      id: 'bar-2',
      x: 200,
      y: 360,
      width: 80,
      height: 80,
      rotation: 0,
      shape: 'circle',
      label: 'B2',
      capacity: 2,
      zone: 'Bar Area',
      color: barZoneColor,
    },
    {
      id: 'bar-3',
      x: 1120,
      y: 220,
      width: 80,
      height: 80,
      rotation: 0,
      shape: 'circle',
      label: 'B3',
      capacity: 2,
      zone: 'Bar Area',
      color: barZoneColor,
    },
    {
      id: 'bar-4',
      x: 1120,
      y: 360,
      width: 80,
      height: 80,
      rotation: 0,
      shape: 'circle',
      label: 'B4',
      capacity: 2,
      zone: 'Bar Area',
      color: barZoneColor,
    },
  ],

  sections: [
    {
      id: 'section-main-dining',
      name: 'Main Dining Hall',
      description: 'Primary dining area with two symmetrical columns of tables',
      x: 280,
      y: 160,
      width: 840,
      height: 1180,
      backgroundColor: 'rgba(34, 197, 94, 0.05)',
      borderColor: 'rgba(34, 197, 94, 0.3)',
      borderWidth: 2,
      borderStyle: 'solid',
      opacity: 0.6,
      sectionType: 'dining',
      displayOrder: 1,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.85)',
      labelSize: 22,
    },
    {
      id: 'section-service-aisle',
      name: 'Service Aisle',
      description: 'Central pathway for staff circulation',
      x: 520,
      y: 160,
      width: 360,
      height: 1180,
      backgroundColor: 'rgba(148, 163, 184, 0.05)',
      borderColor: 'rgba(148, 163, 184, 0.25)',
      borderWidth: 2,
      borderStyle: 'dashed',
      opacity: 0.4,
      sectionType: 'service',
      displayOrder: 2,
      showLabel: true,
      labelColor: 'rgba(71, 85, 105, 0.7)',
      labelSize: 16,
    },
    {
      id: 'section-bar-left',
      name: 'Bar Seating',
      description: 'Additional seating near bar area',
      x: 140,
      y: 180,
      width: 120,
      height: 280,
      backgroundColor: 'rgba(14, 165, 233, 0.08)',
      borderColor: 'rgba(14, 165, 233, 0.35)',
      borderWidth: 2,
      borderStyle: 'dashed',
      opacity: 0.5,
      sectionType: 'bar',
      displayOrder: 3,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.85)',
      labelSize: 14,
    },
    {
      id: 'section-bar-right',
      name: 'Lounge',
      description: 'Casual lounge seating',
      x: 1040,
      y: 180,
      width: 120,
      height: 280,
      backgroundColor: 'rgba(14, 165, 233, 0.08)',
      borderColor: 'rgba(14, 165, 233, 0.35)',
      borderWidth: 2,
      borderStyle: 'dashed',
      opacity: 0.5,
      sectionType: 'bar',
      displayOrder: 4,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.85)',
      labelSize: 14,
    },
  ],

  dividers: [
    // ========================================
    // EXTERIOR WALLS
    // ========================================
    {
      id: 'wall-top',
      type: 'wall',
      x1: 100,
      y1: 100,
      x2: 1300,
      y2: 100,
      thickness: 18,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'wall-left',
      type: 'wall',
      x1: 100,
      y1: 100,
      x2: 100,
      y2: 1380,
      thickness: 18,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'wall-right',
      type: 'wall',
      x1: 1300,
      y1: 100,
      x2: 1300,
      y2: 1380,
      thickness: 18,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'wall-bottom',
      type: 'wall',
      x1: 100,
      y1: 1380,
      x2: 1300,
      y2: 1380,
      thickness: 18,
      color: wallsColor,
      isDoor: false,
    },

    // ========================================
    // ENTRANCE - Wide double doors at bottom center
    // ========================================
    {
      id: 'entrance-door',
      type: 'wall',
      x1: 600,
      y1: 1380,
      x2: 800,
      y2: 1380,
      thickness: 18,
      color: wallsColor,
      isDoor: true,
      doorWidth: 180,
      label: 'Main Entrance',
    },

    // ========================================
    // SERVICE AISLE MARKERS (Subtle guides)
    // ========================================
    {
      id: 'aisle-left-guide',
      type: 'divider',
      x1: 510,
      y1: 160,
      x2: 510,
      y2: 1340,
      thickness: 4,
      color: 'rgba(148, 163, 184, 0.25)',
      isDoor: false,
    },
    {
      id: 'aisle-right-guide',
      type: 'divider',
      x1: 890,
      y1: 160,
      x2: 890,
      y2: 1340,
      thickness: 4,
      color: 'rgba(148, 163, 184, 0.25)',
      isDoor: false,
    },

    // ========================================
    // BAR COUNTER (Top section)
    // ========================================
    {
      id: 'bar-counter',
      type: 'divider',
      x1: 120,
      y1: 150,
      x2: 1280,
      y2: 150,
      thickness: 12,
      color: 'rgba(14, 165, 233, 0.5)',
      isDoor: false,
      label: 'Bar Counter',
    },

    // ========================================
    // DECORATIVE COLUMNS (Visual interest)
    // ========================================
    {
      id: 'column-left-1',
      type: 'column',
      x1: 270,
      y1: 550,
      x2: 270,
      y2: 550,
      thickness: 20,
      color: 'rgba(100, 116, 139, 0.35)',
      isDoor: false,
    },
    {
      id: 'column-left-2',
      type: 'column',
      x1: 270,
      y1: 1050,
      x2: 270,
      y2: 1050,
      thickness: 20,
      color: 'rgba(100, 116, 139, 0.35)',
      isDoor: false,
    },
    {
      id: 'column-right-1',
      type: 'column',
      x1: 1130,
      y1: 550,
      x2: 1130,
      y2: 550,
      thickness: 20,
      color: 'rgba(100, 116, 139, 0.35)',
      isDoor: false,
    },
    {
      id: 'column-right-2',
      type: 'column',
      x1: 1130,
      y1: 1050,
      x2: 1130,
      y2: 1050,
      thickness: 20,
      color: 'rgba(100, 116, 139, 0.35)',
      isDoor: false,
    },
  ],

  decorations: [
    // ========================================
    // ENTRANCE AREA
    // ========================================
    {
      id: 'host-stand',
      type: 'cashier',
      x: 640,
      y: 1310,
      width: 120,
      height: 80,
      rotation: 0,
      label: 'Host Stand',
      color: 'rgba(96, 165, 250, 0.4)',
      icon: '👋',
    },

    // ========================================
    // SERVICE STATIONS (In the central aisle)
    // ========================================
    {
      id: 'service-station-top',
      type: 'fixture',
      x: 650,
      y: 250,
      width: 100,
      height: 75,
      rotation: 0,
      label: 'Service',
      color: 'rgba(34, 197, 94, 0.3)',
      icon: '🍽️',
    },
    {
      id: 'service-station-mid',
      type: 'fixture',
      x: 650,
      y: 700,
      width: 100,
      height: 75,
      rotation: 0,
      label: 'Service',
      color: 'rgba(34, 197, 94, 0.3)',
      icon: '🍽️',
    },
    {
      id: 'service-station-bottom',
      type: 'fixture',
      x: 650,
      y: 1100,
      width: 100,
      height: 75,
      rotation: 0,
      label: 'Service',
      color: 'rgba(34, 197, 94, 0.3)',
      icon: '🍽️',
    },

    // ========================================
    // KITCHEN ACCESS
    // ========================================
    {
      id: 'kitchen-door',
      type: 'kitchen-door',
      x: 1150,
      y: 115,
      width: 120,
      height: 70,
      rotation: 0,
      label: 'Kitchen',
      color: 'rgba(20, 184, 166, 0.35)',
      icon: '👨‍🍳',
    },

    // ========================================
    // RESTROOMS
    // ========================================
    {
      id: 'restrooms',
      type: 'bathroom',
      x: 170,
      y: 1150,
      width: 100,
      height: 80,
      rotation: 0,
      label: 'Restrooms',
      color: 'rgba(148, 163, 184, 0.35)',
      icon: '🚻',
    },

    // ========================================
    // DECORATIVE PLANTS (Symmetrical placement)
    // ========================================
    {
      id: 'plant-entrance-left',
      type: 'plant',
      x: 500,
      y: 1300,
      width: 65,
      height: 65,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.4)',
      icon: '🪴',
    },
    {
      id: 'plant-entrance-right',
      type: 'plant',
      x: 835,
      y: 1300,
      width: 65,
      height: 65,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.4)',
      icon: '🪴',
    },
    {
      id: 'plant-left-1',
      type: 'plant',
      x: 260,
      y: 350,
      width: 55,
      height: 55,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.35)',
      icon: '🌿',
    },
    {
      id: 'plant-left-2',
      type: 'plant',
      x: 260,
      y: 850,
      width: 55,
      height: 55,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.35)',
      icon: '🌿',
    },
    {
      id: 'plant-right-1',
      type: 'plant',
      x: 1085,
      y: 350,
      width: 55,
      height: 55,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.35)',
      icon: '🌿',
    },
    {
      id: 'plant-right-2',
      type: 'plant',
      x: 1085,
      y: 850,
      width: 55,
      height: 55,
      rotation: 0,
      label: '',
      color: 'rgba(74, 222, 128, 0.35)',
      icon: '🌿',
    },

    // ========================================
    // AMBIENT LIGHTING (Chandeliers)
    // ========================================
    {
      id: 'chandelier-1',
      type: 'fixture',
      x: 375,
      y: 450,
      width: 60,
      height: 60,
      rotation: 0,
      label: '',
      color: 'rgba(251, 191, 36, 0.35)',
      icon: '💡',
    },
    {
      id: 'chandelier-2',
      type: 'fixture',
      x: 375,
      y: 900,
      width: 60,
      height: 60,
      rotation: 0,
      label: '',
      color: 'rgba(251, 191, 36, 0.35)',
      icon: '💡',
    },
    {
      id: 'chandelier-3',
      type: 'fixture',
      x: 965,
      y: 450,
      width: 60,
      height: 60,
      rotation: 0,
      label: '',
      color: 'rgba(251, 191, 36, 0.35)',
      icon: '💡',
    },
    {
      id: 'chandelier-4',
      type: 'fixture',
      x: 965,
      y: 900,
      width: 60,
      height: 60,
      rotation: 0,
      label: '',
      color: 'rgba(251, 191, 36, 0.35)',
      icon: '💡',
    },

    // ========================================
    // FEATURE ARTWORK
    // ========================================
    {
      id: 'artwork-main',
      type: 'artwork',
      x: 590,
      y: 120,
      width: 220,
      height: 90,
      rotation: 0,
      label: 'Feature Wall Art',
      color: 'rgba(244, 114, 182, 0.3)',
      icon: '🖼️',
    },
  ],
};
