import type {
  FloorPlanTable,
  FloorPlanSection,
  FloorPlanDivider,
  FloorPlanDecoration,
  FloorPlanMetadata,
} from '@/store/api/floorPlansApi';

export interface FloorPlanTemplate {
  name: string;
  description: string;
  tables: FloorPlanTable[];
  sections: FloorPlanSection[];
  dividers: FloorPlanDivider[];
  decorations: FloorPlanDecoration[];
  metadata: FloorPlanMetadata;
}

const wallsColor = 'rgba(30, 41, 59, 0.45)';
const mainDiningColor = 'rgba(34, 197, 94, 0.16)';
const barZoneColor = 'rgba(14, 165, 233, 0.18)';
const privateZoneColor = 'rgba(239, 68, 68, 0.16)';

export const CLASSIC_RESTAURANT_TEMPLATE: FloorPlanTemplate = {
  name: 'Classic Restaurant Layout',
  description:
    'Pre-built restaurant template with a main dining hall, bar lounge, private dining, and service stations.',
  metadata: {
    canvasWidth: 1200,
    canvasHeight: 800,
    backgroundColor: 'hsl(var(--background))',
    backgroundImage: undefined,
    gridSize: 1,
    showGrid: true,
    zoomLevel: 1,
  },
  tables: [
    // Main dining rows
    {
      id: 'template-table-1',
      x: 260,
      y: 220,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T1',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-2',
      x: 410,
      y: 220,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T2',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-3',
      x: 560,
      y: 220,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T3',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-4',
      x: 710,
      y: 220,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T4',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-5',
      x: 260,
      y: 360,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T5',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-6',
      x: 410,
      y: 360,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T6',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-7',
      x: 560,
      y: 360,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T7',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    {
      id: 'template-table-8',
      x: 710,
      y: 360,
      width: 110,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'T8',
      capacity: 4,
      zone: 'Main Dining',
      color: mainDiningColor,
    },
    // Banquette
    {
      id: 'template-table-9',
      x: 880,
      y: 250,
      width: 140,
      height: 70,
      rotation: 0,
      shape: 'rectangle',
      label: 'B1',
      capacity: 6,
      zone: 'Banquette',
      color: 'rgba(244, 114, 182, 0.16)',
    },
    {
      id: 'template-table-10',
      x: 880,
      y: 340,
      width: 140,
      height: 70,
      rotation: 0,
      shape: 'rectangle',
      label: 'B2',
      capacity: 6,
      zone: 'Banquette',
      color: 'rgba(244, 114, 182, 0.16)',
    },
    // Bar lounge high-tops
    {
      id: 'template-table-11',
      x: 200,
      y: 520,
      width: 90,
      height: 90,
      rotation: 0,
      shape: 'circle',
      label: 'H1',
      capacity: 3,
      zone: 'Bar Lounge',
      color: barZoneColor,
    },
    {
      id: 'template-table-12',
      x: 320,
      y: 520,
      width: 90,
      height: 90,
      rotation: 0,
      shape: 'circle',
      label: 'H2',
      capacity: 3,
      zone: 'Bar Lounge',
      color: barZoneColor,
    },
    {
      id: 'template-table-13',
      x: 440,
      y: 520,
      width: 90,
      height: 90,
      rotation: 0,
      shape: 'circle',
      label: 'H3',
      capacity: 3,
      zone: 'Bar Lounge',
      color: barZoneColor,
    },
    // Private dining tables
    {
      id: 'template-table-14',
      x: 900,
      y: 520,
      width: 120,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'P1',
      capacity: 6,
      zone: 'Private Dining',
      color: privateZoneColor,
    },
    {
      id: 'template-table-15',
      x: 1040,
      y: 520,
      width: 120,
      height: 80,
      rotation: 0,
      shape: 'rectangle',
      label: 'P2',
      capacity: 6,
      zone: 'Private Dining',
      color: privateZoneColor,
    },
  ],
  sections: [
    {
      id: 'template-section-main',
      name: 'Main Dining',
      description: 'Primary dining area with standard four-top tables.',
      x: 180,
      y: 140,
      width: 620,
      height: 320,
      backgroundColor: 'rgba(34, 197, 94, 0.08)',
      borderColor: 'rgba(34, 197, 94, 0.35)',
      borderWidth: 2,
      borderStyle: 'solid',
      opacity: 0.5,
      sectionType: 'dining',
      displayOrder: 1,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.8)',
      labelSize: 18,
    },
    {
      id: 'template-section-bar',
      name: 'Bar Lounge',
      description: 'High-top lounge tables near the bar counter.',
      x: 140,
      y: 460,
      width: 360,
      height: 160,
      backgroundColor: 'rgba(14, 165, 233, 0.08)',
      borderColor: 'rgba(14, 165, 233, 0.35)',
      borderWidth: 2,
      borderStyle: 'dashed',
      opacity: 0.5,
      sectionType: 'bar',
      displayOrder: 2,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.8)',
      labelSize: 16,
    },
    {
      id: 'template-section-private',
      name: 'Private Dining',
      description: 'Reserved private dining room for events.',
      x: 820,
      y: 460,
      width: 360,
      height: 200,
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
      borderColor: 'rgba(239, 68, 68, 0.35)',
      borderWidth: 2,
      borderStyle: 'solid',
      opacity: 0.5,
      sectionType: 'private',
      displayOrder: 3,
      showLabel: true,
      labelColor: 'rgba(15, 23, 42, 0.8)',
      labelSize: 16,
    },
  ],
  dividers: [
    // outer walls
    {
      id: 'template-divider-wall-top',
      type: 'wall',
      x1: 140,
      y1: 120,
      x2: 1080,
      y2: 120,
      thickness: 12,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'template-divider-wall-left',
      type: 'wall',
      x1: 140,
      y1: 120,
      x2: 140,
      y2: 680,
      thickness: 12,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'template-divider-wall-right',
      type: 'wall',
      x1: 1080,
      y1: 120,
      x2: 1080,
      y2: 680,
      thickness: 12,
      color: wallsColor,
      isDoor: false,
    },
    {
      id: 'template-divider-wall-bottom',
      type: 'wall',
      x1: 140,
      y1: 680,
      x2: 1080,
      y2: 680,
      thickness: 12,
      color: wallsColor,
      isDoor: false,
    },
    // doorway entrance
    {
      id: 'template-divider-entrance',
      type: 'wall',
      x1: 560,
      y1: 680,
      x2: 680,
      y2: 680,
      thickness: 12,
      color: wallsColor,
      isDoor: true,
      doorWidth: 100,
    },
    // bar counter
    {
      id: 'template-divider-bar',
      type: 'divider',
      x1: 120,
      y1: 440,
      x2: 520,
      y2: 440,
      thickness: 8,
      color: 'rgba(2, 132, 199, 0.45)',
      isDoor: false,
    },
    // private room partition
    {
      id: 'template-divider-private',
      type: 'divider',
      x1: 780,
      y1: 440,
      x2: 1150,
      y2: 440,
      thickness: 8,
      color: 'rgba(185, 28, 28, 0.45)',
      isDoor: true,
      doorWidth: 80,
    },
  ],
  decorations: [
    {
      id: 'template-decoration-host',
      type: 'cashier',
      x: 620,
      y: 640,
      width: 80,
      height: 60,
      rotation: 0,
      label: 'Host Stand',
      color: 'rgba(96, 165, 250, 0.3)',
      icon: '👋',
    },
    {
      id: 'template-decoration-kitchen',
      type: 'kitchen-door',
      x: 1040,
      y: 160,
      width: 120,
      height: 60,
      rotation: 0,
      label: 'Kitchen',
      color: 'rgba(14, 116, 144, 0.24)',
      icon: '🍳',
    },
    {
      id: 'template-decoration-wait-station',
      type: 'fixture',
      x: 520,
      y: 520,
      width: 80,
      height: 60,
      rotation: 0,
      label: 'Wait Station',
      color: 'rgba(34, 197, 94, 0.22)',
      icon: '🧾',
    },
    {
      id: 'template-decoration-restrooms',
      type: 'fixture',
      x: 260,
      y: 160,
      width: 100,
      height: 60,
      rotation: 0,
      label: 'Restrooms',
      color: 'rgba(234, 179, 8, 0.26)',
      icon: '🚻',
    },
  ],
};

